version: '2.4'
services:
  octoprint:
    build:
      context: .
      target: octoprint
    restart: always
    labels:
      - "traefik.frontend.rule=Host:prusa.ciaranmcnulty.com"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.protocol=http"
    devices:
      - /dev/video0
      - /dev/ttyACM0
    volumes:
      - /mnt/octoprint:/data
    env_file:
      - power-device.env
    environment:
      - POWER_HOST=${HOST}
      - POWER_PORT=3000

  reverse-proxy:
    image: traefik
    restart: always
    command: --api --docker
    ports:
      - "80:80"     # The HTTP
      - "443:443"   # SSL
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

  dynamic-dns-updater:
    image: oznu/cloudflare-ddns:armhf
    restart: always
    env_file: 
      - cloudflare.env

  power-controller:
    image: arhea/tplink-hs100-hub:armhf
    network_mode: host

